// Generated by CoffeeScript 1.10.0
(function() {
  var ForecastIOInterface;

  window.ForecastIOInterface = ForecastIOInterface = (function() {
    ForecastIOInterface.prototype.api_key = "";

    ForecastIOInterface.prototype.api_url = "https://api.forecast.io/forecast/";

    function ForecastIOInterface() {
      console.log("FIO Interface constructed");
    }

    ForecastIOInterface.prototype.query = function(lat, lng, cbfn) {
      var data, latitude, longitude, url;
      latitude = String(lat);
      longitude = String(lng);
      debugger;
      url = this.api_url + this.api_key + "/" + latitude + "," + longitude;
      console.log("Hitting up: ", url);
      data = void 0;
      if (typeof cbfn === "function") {
        return cbfn(data);
      }
    };

    return ForecastIOInterface;

  })();

}).call(this);
