// Generated by CoffeeScript 1.10.0
(function() {
  var ForecastIOInterface;

  window.ForecastIOInterface = ForecastIOInterface = (function() {
    ForecastIOInterface.prototype.api_key = "3587b2d6d9318e9df488d17a2f41c088";

    ForecastIOInterface.prototype.api_url = "https://api.forecast.io/forecast/";

    function ForecastIOInterface() {
      console.log("FIO Interface constructed");
    }

    ForecastIOInterface.prototype.query = function(lat, lng, cbfn) {
      var latitude, longitude, url;
      latitude = String(lat);
      longitude = String(lng);
      url = this.api_url + this.api_key + "/" + latitude + "," + longitude;
      return $.ajax({
        type: "GET",
        url: url,
        dataType: "jsonp",
        success: (function(_this) {
          return function(data) {
            if (typeof cbfn === "function") {
              return cbfn(data);
            }
          };
        })(this),
        error: (function(_this) {
          return function(uhh) {
            if (typeof cbfn === "function") {
              return cbfn(void 0);
            }
          };
        })(this)
      });
    };

    return ForecastIOInterface;

  })();

}).call(this);
