// Generated by CoffeeScript 1.10.0
(function() {
  $(function() {
    console.log("You should probably make this do something. Something impressive preferably.");
    window.fioi = new ForecastIOInterface();
    return $('#submit').on('click', function(e) {
      var lat, lng;
      e.preventDefault();
      e.stopPropagation();
      lat = $('#lat').val();
      lng = $('#lng').val();
      return fioi.query(lat, lng, function(data) {
        return console.log("GOT SOME DATA: ", data);
      });
    });
  });

}).call(this);
